name: Deploy
on:
    push:
        branches:
        - master
  id: deploy
  uses: Pendect/action-rsyncer@v1.1.0
  env:
    DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
  with:
    flags: '-avzr --delete'
    options: ''
    ssh_options: ''
    src: '/'
    dest: 'root@"${{secrets.SERVER_IP}}":/var/www/frontend_development'

- name: Display status from deploy
  run: echo "${{ steps.deploy.outputs.status }}"