# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy app to Azure Web App - FrontEnd-Artemis-Project1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'FrontEnd-Artemis-Project1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9302b1da4dda4eb0bbbfd7a636282230 }}
        package: .